
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int ADMI_C = 9;
  public static final int COSO_N = 18;
  public static final int MENOS = 12;
  public static final int PUNTO = 5;
  public static final int PUNTOYCOMA = 7;
  public static final int CADENA = 23;
  public static final int DOSPUNTOS = 8;
  public static final int CONJUNTO = 19;
  public static final int OR = 16;
  public static final int LETRA = 21;
  public static final int DPORCIENTO = 17;
  public static final int ID = 22;
  public static final int POR = 13;
  public static final int INTE_C = 10;
  public static final int COMA = 6;
  public static final int MAYOR = 4;
  public static final int EOF = 0;
  public static final int DIGITO = 20;
  public static final int DIV = 14;
  public static final int error = 1;
  public static final int CONTRADIV = 15;
  public static final int LLAVE_C = 3;
  public static final int LLAVE_A = 2;
  public static final int MAS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVE_A",
  "LLAVE_C",
  "MAYOR",
  "PUNTO",
  "COMA",
  "PUNTOYCOMA",
  "DOSPUNTOS",
  "ADMI_C",
  "INTE_C",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "CONTRADIV",
  "OR",
  "DPORCIENTO",
  "COSO_N",
  "CONJUNTO",
  "DIGITO",
  "LETRA",
  "ID",
  "CADENA"
  };
}

