
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int ADMI_C = 12;
  public static final int COSO_N = 21;
  public static final int MENOS = 15;
  public static final int MENOR = 6;
  public static final int PUNTO = 8;
  public static final int PUNTOYCOMA = 10;
  public static final int CADENA = 31;
  public static final int DOSPUNTOS = 11;
  public static final int CONJUNTO = 27;
  public static final int IGUAL = 22;
  public static final int OR = 19;
  public static final int LETRA = 29;
  public static final int COMENTARIO_LINEA = 32;
  public static final int COMENTARIO_VARIASL = 33;
  public static final int CORH_C = 24;
  public static final int CORH_A = 23;
  public static final int PAR_C = 26;
  public static final int PAR_A = 25;
  public static final int DPORCIENTO = 20;
  public static final int ID = 30;
  public static final int POR = 16;
  public static final int INTE_C = 13;
  public static final int COMA = 9;
  public static final int MAYOR = 7;
  public static final int EOF = 0;
  public static final int DIGITO = 28;
  public static final int DIV = 17;
  public static final int CONTRADIV = 18;
  public static final int error = 1;
  public static final int LLAVE_C = 3;
  public static final int LLAVE_A = 2;
  public static final int MAS = 14;
  public static final int COMILLADOB = 5;
  public static final int COMILLASIM = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVE_A",
  "LLAVE_C",
  "COMILLASIM",
  "COMILLADOB",
  "MENOR",
  "MAYOR",
  "PUNTO",
  "COMA",
  "PUNTOYCOMA",
  "DOSPUNTOS",
  "ADMI_C",
  "INTE_C",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "CONTRADIV",
  "OR",
  "DPORCIENTO",
  "COSO_N",
  "IGUAL",
  "CORH_A",
  "CORH_C",
  "PAR_A",
  "PAR_C",
  "CONJUNTO",
  "DIGITO",
  "LETRA",
  "ID",
  "CADENA",
  "COMENTARIO_LINEA",
  "COMENTARIO_VARIASL"
  };
}

